---
title: "p8105_hw2"
output: github_document
---

```{r, setup}
library(tidyverse)
library(janitor)
```

## Problem 1

```{r}
pols_data = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(month = recode(month, `01` = "january", `02` = "february", `03` = "march", `04` = "april", `05` = "may", `06` = "june", `07` = "july", `08` = "august", `09` = "september", `10` = "october", `11` = "november", `12` = "december")) %>% 
  pivot_longer(
    cols = c(prez_gop, prez_dem),
    names_to = "president",
    values_to = "prez_words") %>%  
  select(-day) %>% 
  pivot_longer(
    cols = c(gov_gop, gov_dem),
    names_to = "governor",
    values_to = "gov_words") %>% 
  pivot_longer(
    cols = c(sen_gop, sen_dem),
    names_to = "senator",
    values_to = "sen_words") %>% 
  pivot_longer(
    cols = c(rep_gop, rep_dem),
    names_to = "representative",
    values_to = "rep_words"
  )
```

```{r}
unemployment_data =
  read_csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month") %>% 
  mutate(month = recode(month, `jan` = "january", `feb` = "february", `mar` = "march", `apr` = "april", `may` = "may", `jun` = "june", `jul` = "july", `aug` = "august", `sep` = "september", `oct` = "october", `nov` = "november", `dec` = "december"))
```

```{r}
snp_data = 
  read_csv("./fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(month = recode(month, `1` = "january", `2` = "february", `3` = "march", `4` = "april", `5` = "may", `6` = "june", `7` = "july", `8` = "august", `9` = "september", `10` = "october", `11` = "november", `12` = "december")) %>% 
  select(-day) %>% 
  mutate(year = str_pad(year, width = 2, pad = "0")) %>% 
  mutate(year = paste0("20", year))
```

```{r}
p_and_s_data = 
  full_join(
    (pols_data %>% 
       mutate(year = as.integer(year))),
    (snp_data %>% 
      mutate(year = as.integer(year))), 
    by = c("year", "month"))
```

```{r}
pus_data = 
  full_join(
    (p_and_s_data %>% 
      mutate(year = as.integer(year))),
    (unemployment_data %>% 
       mutate(year = as.integer(year))),
    by = c("year", "month"))
```

## Problem 2

```{r}
mr_trash_wheel = 
  readxl::read_excel(
    path = "./202409 Trash Wheel Collection Data.xlsx", 
    sheet = "Mr. Trash Wheel",
    range = "A2:N653") %>% 
  janitor::clean_names() %>% 
  mutate(sports_balls = as.integer(sports_balls)) %>% 
  mutate(homes_powered = as.integer(homes_powered)) %>% 
  select(-year, -month)
```

```{r}
prof_trash_wheel = 
  readxl::read_excel(
    path = "./202409 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M120") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered = as.integer(homes_powered)) %>% 
  select(-year, -month)
```

```{r}
gwynnda_trash_wheel = 
  readxl::read_excel(
    path = "./202409 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda Trash Wheel",
    range = "A2:L265") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered = as.integer(homes_powered)) %>% 
  select(-year, -month)
```

```{r}
trash_wheel = 
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwynnda_trash_wheel)
  by = c("day")
```

